chore(infra): fix deploy action

diff --git a/.github/workflows/test_build.yaml b/.github/workflows/test_build.yaml
--- a/.github/workflows/test_build.yaml
+++ b/.github/workflows/test_build.yaml
@@ -6,28 +6,130 @@ on:
   pull_request:
 
 jobs:
-  test_build:
-    name: Test Image Build
+  test_build_base:
+    name: Test Build Base
     uses: sdr-enthusiasts/common-github-workflows/.github/workflows/sdre.yml@b74159859e761398e31593ee81fd411fd96d69fc # main
     with:
       push_enabled: false
       ghcr_repo_owner: ${{ github.repository_owner }}
       ghcr_repo: ${{ github.repository }}
-      docker_build_file: Dockerfile
+      build_with_tmpfs: false
+      build_latest: true
+      docker_latest_tag: base
+      docker_build_file: Dockerfile.base
+    secrets:
+      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
+
+  test_build_mlat_client:
+    name: Test Build Mlat Client
+    needs: [test_build_base]
+    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/sdre.yml@b74159859e761398e31593ee81fd411fd96d69fc # main
+    with:
+      push_enabled: false
+      ghcr_repo_owner: ${{ github.repository_owner }}
+      ghcr_repo: ${{ github.repository }}
+      build_with_tmpfs: false
+      build_latest: true
+      docker_latest_tag: mlatclient
+      docker_build_file: Dockerfile.mlatclient
+    secrets:
+      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
+
+  test_build_planefence_base:
+    name: Test Build Planefence Base
+    needs: [test_build_base]
+    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/sdre.yml@b74159859e761398e31593ee81fd411fd96d69fc # main
+    with:
+      push_enabled: false
+      ghcr_repo_owner: ${{ github.repository_owner }}
+      ghcr_repo: ${{ github.repository }}
+      build_with_tmpfs: false
+      build_latest: true
+      docker_latest_tag: planefence_base
+      docker_build_file: Dockerfile.planefence_base
+    secrets:
+      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
+
+  test_build_soapy_full:
+    name: Test Build Soapy Full
+    needs: [test_build_base]
+    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/sdre.yml@b74159859e761398e31593ee81fd411fd96d69fc # main
+    with:
+      push_enabled: false
+      ghcr_repo_owner: ${{ github.repository_owner }}
+      ghcr_repo: ${{ github.repository }}
+      build_with_tmpfs: false
+      build_latest: true
+      docker_latest_tag: soapy-full
+      docker_build_file: Dockerfile.soapy-full
+    secrets:
+      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
+
+  test_build_wreadsb:
+    name: Test Build Wreadsb
+    needs: [test_build_base, test_build_mlat_client]
+    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/sdre.yml@b74159859e761398e31593ee81fd411fd96d69fc # main
+    with:
+      push_enabled: false
+      ghcr_repo_owner: ${{ github.repository_owner }}
+      ghcr_repo: ${{ github.repository }}
+      build_with_tmpfs: false
+      build_latest: true
+      docker_latest_tag: wreadsb
+      docker_build_file: Dockerfile.wreadsb
+    secrets:
+      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
+
+  test_build_acars-decoder-soapy:
+    name: Test Build ACARS Decoder Soapy
+    needs: [test_build_wreadsb]
+    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/sdre.yml@b74159859e761398e31593ee81fd411fd96d69fc # main
+    with:
+      push_enabled: false
+      ghcr_repo_owner: ${{ github.repository_owner }}
+      ghcr_repo: ${{ github.repository }}
+      build_with_tmpfs: false
+      build_latest: true
+      docker_latest_tag: acars-decoder-soapy
+      docker_build_file: Dockerfile.acars-decoder-soapy
+    secrets:
+      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
+
+  test_build_dump978-full:
+    name: Test Build Dump978 Full
+    needs: [test_build_wreadsb]
+    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/sdre.yml@b74159859e761398e31593ee81fd411fd96d69fc # main
+    with:
+      push_enabled: false
+      ghcr_repo_owner: ${{ github.repository_owner }}
+      ghcr_repo: ${{ github.repository }}
+      build_with_tmpfs: false
+      build_latest: true
+      docker_latest_tag: dump978-full
+      docker_build_file: Dockerfile.dump978-full
     secrets:
       ghcr_token: ${{ secrets.GITHUB_TOKEN }}
 
   require_test_build_success:
     name: Require test_build success
     runs-on: ubuntu-latest
-    needs: [test_build]
+    needs:
+      - test_build_base
+      - test_build_mlat_client
+      - test_build_planefence_base
+      - test_build_soapy_full
+      - test_build_wreadsb
+      - test_build_acars-decoder-soapy
+      - test_build_dump978-full
     if: always()
     steps:
-      - name: Fail if test_build did not succeed
+      - name: Fail if any test_build did not succeed
         run: |
-          echo "test_build result: ${{ needs.test_build.result }}"
-
-          if [ "${{ needs.test_build.result }}" != "success" ]; then
-            echo "::error::test_build workflow did not fully succeed"
-            exit 1
-          fi
+          RESULTS="${{ join(needs.*.result, ' ') }}"
+          echo "Job results: $RESULTS"
+          for result in $RESULTS; do
+            if [ "$result" != "success" ]; then
+              echo "::error::A test_build workflow did not fully succeed"
+              exit 1
+            fi
+          done
